{
 "title": "Restic Backup",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Backup Job Duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "alias": "$tag_repo",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "repo" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "restic",
     "query": "SELECT sum(\"value\") FROM \"restic_value\" WHERE (\"summary_attr\" = 'files_changed') AND $timeFilter GROUP BY time($__interval), \"snapshot\"",
     "select": [
      [
       { "params": [ "total_duration" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "summary" }
     ]
    }
   ]
  },
  {
   "title": "Backup data added",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_repo",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "repo" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "restic",
     "select": [
      [
       { "params": [ "data_added" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "summary" }
     ]
    }
   ]
  },
  {
   "title": "Backuped data size",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_repo",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "repo" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "restic",
     "query": "SELECT sum(\"value\") FROM \"restic_value\" WHERE (\"summary_attr\" = 'total_bytes_processed') AND $timeFilter GROUP BY time(1d), \"repo\" fill(null) ",
     "select": [
      [
       { "params": [ "total_bytes_processed" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "summary" }
     ]
    }
   ]
  },
  {
   "title": "Backuped files",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" }
     ],
     "measurement": "restic",
     "query": "SELECT sum(\"files_unmodified\") AS \"unmodified\", sum(\"files_changed\") AS \"changed\", sum(\"files_new\") AS \"new\" FROM \"restic\" WHERE $timeFilter GROUP BY time(1d)",
     "select": [
      [
       { "params": [ "files_unmodified" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "unmodified" ], "type": "alias" }
      ],
      [
       { "params": [ "files_changed" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "changed" ], "type": "alias" }
      ],
      [
       { "params": [ "files_new" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "new" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "summary" }
     ]
    }
   ]
  },
  {
   "title": "Current backup",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "restic",
     "select": [
      [
       { "params": [ "percent_done" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "repo" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "status" }
     ]
    }
   ]
  },
  {
   "title": "Bytes processed",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "restic",
     "select": [
      [
       { "params": [ "bytes_done" ], "type": "field" },
       { "params": [ "*0" ], "type": "math" }
      ],
      [
       { "params": [ "total_bytes" ], "type": "field" }
      ],
      [
       { "params": [ "bytes_done" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "status" }
     ]
    }
   ]
  },
  {
   "title": "Files processed",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "restic",
     "select": [
      [
       { "params": [ "files_done" ], "type": "field" },
       { "params": [ "*0" ], "type": "math" }
      ],
      [
       { "params": [ "total_files" ], "type": "field" }
      ],
      [
       { "params": [ "files_done" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "status" }
     ]
    }
   ]
  },
  {
   "title": "ETA",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 14, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocalNoDateIfToday" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "restic",
     "query": "SELECT time + 123 AS foo , \"seconds_remaining\" FROM \"restic\" WHERE (\"type\" = 'status') AND $timeFilter",
     "select": [
      [
       { "params": [ "seconds_remaining" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "*1000" ], "type": "math" },
       { "params": [ "remain" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "status" }
     ]
    }
   ]
  },
  {
   "title": "Error count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "restic",
     "query": "SELECT last(\"seconds_remaining\") FROM \"restic\" WHERE (\"type\" = 'status') AND $timeFilter",
     "select": [
      [
       { "params": [ "error_count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "status" }
     ]
    }
   ]
  },
  {
   "title": "Total duration so far",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 14, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "restic",
     "query": "SELECT last(\"seconds_remaining\") FROM \"restic\" WHERE (\"type\" = 'status') AND $timeFilter",
     "select": [
      [
       { "params": [ "seconds_elapsed" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "status" }
     ]
    }
   ]
  },
  {
   "title": "Current file processed",
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "restic",
     "query": "SELECT last(\"seconds_remaining\") FROM \"restic\" WHERE (\"type\" = 'status') AND $timeFilter",
     "select": [
      [
       { "params": [ "current_files" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "status" }
     ]
    }
   ]
  },
  {
   "title": "Latest backup jobs",
   "type": "table-old",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 38 },
   "targets": [
    {
     "alias": "$col",
     "measurement": "restic",
     "query": "SELECT \"total_duration\", \"total_files_processed\", \"snapshot\", \"repo\" FROM \"restic\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "repo" ], "type": "field" },
       { "params": [ "Repository" ], "type": "alias" }
      ],
      [
       { "params": [ "snapshot" ], "type": "field" },
       { "params": [ "Snapshot" ], "type": "alias" }
      ],
      [
       { "params": [ "total_duration" ], "type": "field" }
      ],
      [
       { "params": [ "total_bytes_processed" ], "type": "field" }
      ],
      [
       { "params": [ "data_added" ], "type": "field" }
      ],
      [
       { "params": [ "files_changed" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "summary" }
     ]
    }
   ]
  }
 ]
}